### ISSUE TITLE
what does omc_1 mean? 

### ISSUE THREAD

**Issue by mathTaoTao** [zhixy/Laser-Camera-Calibration-Toolbox#1]
Hi, what does omc_1 mean in the Calib_Results.m, according to your comment, it means rotation vector, but shouldn't the rotation parameters be a 3*3 matrix? Thanks.

**Comment by zhixy** [comment]
there are several methods to represent rotation: 3*3 matrix, Euler angles, axis-angle, quaternion. If I am right, omc_1 may be Euler angles. In fact, the Calib_Results.m is generated using the [camera calibration toolbox](http://www.vision.caltech.edu/bouguetj/calib_doc/), you can just use it, and don't need pay much attention to its content.

**Comment by mathTaoTao** [comment]
I use the param fc and cc in Calib_Results.m as camera intrinsic  parameters M1, and the R, t in Laser_Cam_calib_2.m as extrinsic parameters M2. I try to project the laser cloud point in sample_data/laser_target1.xyz to pixel, here M=M1*M2.inverse, however, the pixels are out of  range of (640,480). Any problem?

**Comment by zhixy** [comment]
It seems right, but you should take care of M2, making sure it transform the  3D points correctly from the laser frame to camera frame. On the other hand, are only a few points out of range? If so, maybe it's right, because it is possible that some points are beyond the view of the camera

**Comment by mathTaoTao** [comment]
Thanks! Here M=M1*M2, and I filtered the invalid points, I  think I have got the right result.

**Comment by zhixy** [comment]
OK, good.
