### ISSUE TITLE
VLP-16 Velodyne LiDAR can't work

### ISSUE THREAD

**Issue by pacientes** [zhixy/Laser-Camera-Calibration-Toolbox#3]
hello, i'm using velodyne VLP-16 LiDAR.

when i do calibrate camera and lidar data,
i have a error message about 

'Index exceeds matrix dimensions.

Error in ObtainPlanePoint (line 18)
        index_samples = temp(1:n_samples);

Error in select_plane_from_point_cloud/continue_callback (line 30)
            [theta, alpha, minError, inliers] = ObtainPlanePoint(pc.Location,cur_info.Position);
 
Error using uiwait (line 81)
Error while evaluating UIControl Callback.
'

so. what can i do next step?

**Comment by crankler** [comment]
Hi, can you share your method for obtaining the laser.xyz, I can;t get the blank in chessboard? Thank you!
